name: Build and Update

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-jar
        path: ./target/JJsPlugin-1.0.jar

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download JAR artifact
      uses: actions/download-artifact@v3
      with:
        name: plugin-jar
    
    - name: Upload plugin to FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_PATH: ${{ secrets.FTP_PATH }}
      run: |
        curl -T JJsPlugin-1.0.jar sftp://$FTP_SERVER/$FTP_PATH/ --user $FTP_USERNAME:$FTP_PASSWORD --insecure
